### ISSUE TITLE
Smart Wheelchair

### ISSUE THREAD

**Issue by DionesSouza** [arjunsengupta1998/Iris-controlled-Smart-wheelchair-for-paralysis-patients#1]
Hello
My name is Diones Souza, I'm from Brazil and I'm an engineering student.
I'm trying to apply your algorithm: Iris Controlled Smart Wheelchair for paralysis patients,
in a wheelchair. So I would like to know if you have already made any changes to the algorithm?
Because this is giving some inconsistency, it is not precisely locating the direction of the iris.
Please, contact me by email: dionessouza12@gmail.com

Thanks in advance for your support and understanding.

**Comment by arjunsengupta98** [comment]
Hey there.

Sorry for the massively late response, I completely missed your message. I believe that you may have already accomplished your purpose in these past months.

For the benefit of other readers - 

The accuracy was substantially improved. The code can be found in my other repository - https://github.com/arjunsengupta98/-Eye-controlled-computer-navigation-system-.git 

It uses the same algorithm for detection of iris position, but I have used additional filters which improves the accuracy in various lighting conditions. You may copy that section of the code from here and replace it in eyeClient.py

FYI I have stopped work on this project - I had developed it during my undergrad college days to learn the applications of openCV and python programming in general, but now I'm completely occupied with my current job. (I'm a professional developer now working on robotics, so feel free to reach out - I shall respond as and when I get time)

Cheers!
